### ISSUE TITLE
Non-generic Count methods aren't actually doing a count

### ISSUE THREAD

**Issue by cdonnellytx** [dallasbeek/Dapper.Database#14]
The non-generic `Count` methods in `SqlDatabase` (and their async counterparts) aren't doing a proper count of objects, but rather calling `ExecuteScalar` without wrapping the SQL.  There's also no tests covering them.

I'm not sure what the best fix is here because the generic `Count<T>` methods generate the SQL by getting the table info for the given type.  Thoughts?

**Comment by dallasbeek** [comment]
addressed via https://github.com/dallasbeek/Dapper.Database/commit/82886953d7e7bd8a88d6bfebba00ff764d4a4dc5

**Comment by dallasbeek** [comment]
and https://github.com/dallasbeek/Dapper.Database/commit/428ea9e1c39ed93d0b9b1e418ec86d5b6168ea0f

**Comment by cdonnellytx** [comment]
awesome, thanks!
