### ISSUE TITLE
TypeHandler Attribute (feature)

### ISSUE THREAD

**Issue by gt6796c** [dallasbeek/Dapper.Database#16]
Would you consider adding a class attribute for TypeHandlers so that your extension could handle registration via `SqlMapper.AddTypeHandler()` as part of your metadata gathering process during the population of TableInfoCache.?

```
[TypeHandler(new XmlTypeHandler())]
public class SomeClassSerializedAsXmlInDB
{
  [Key]
  public int Id {get;set}
}
```
If you're interested, I can put together a PR for it.

**Comment by dallasbeek** [comment]
Depends, where would the XmlTypeHandler exist?  Inside Dapper.Database or external?  I don't mind the idea of registering the handlers but not so much the idea of maintaining them.

**Comment by gt6796c** [comment]
`XmlTypeHandler` (or any handler) would be external to `Dapper.Database` (That particular one can be found in `Dapper`, somewhere... It's just serialization interface `ITypeHandler` that they have...) 

`Dapper.Database` would provide two things: 1) the attribute and 2) the "hook up".

**Comment by dallasbeek** [comment]
I see value in this.  Have been thinking about xml database type and sql server as I often times will store structured data in an xml column.  Would there be an ability to map it at a property level?

```
public class SomeClass
{
  [Key]
  public int Id {get;set}

  [TypeHandler(new GeographyHandler())]
  public Point Coordinant { get; set; }
}
```

**Comment by gt6796c** [comment]
I personally would love this to be at the attribute level, but I have only gotten this to work with Dapper at the Type level... So I've found where you could call `Dapper.SqlMapper.AddTypeHandler(typeof(Point), new GeographyHandler())` but not where you get more granular than that. So every `Point` would be handled this way, not just `SomeClass.Coordinate`

**Comment by dallasbeek** [comment]
Given this is a global registration it feels strange to me that TableInfo would register a type handler when it incidentally encounters one.  I can see where this may create some side effects when (for whatever reason) the solution is using more than one database.  I've learned this from the GuidTypeHandler.  I do have a vested interest in xml columns on Sql Server so will work out some thoughts in a branch and come back to you.

**Comment by gt6796c** [comment]
I agree that the property-level attribute might be too much given how it works on the Dapper side, but the class level attribute seems to fit in with Dapper's capabilities and isn't just incidental. It'd be a new attribute that solely exists to let people do this global mapping. In the case of DTOs and the like, this seems quite reasonable.
