### ISSUE TITLE
Include Private properties in the mapping

### ISSUE THREAD

**Issue by Jetski5822** [dallasbeek/Dapper.Database#19]
At the moment you exclude private properties... Could you allow us to expose them?

```
public class Foo {

    [Column("some_obsceue_name")]
   private string Blah {get;set;}

   public bool IsBlah => Blah == "Y";

}
```

It would help massively to work with old database

**Comment by dallasbeek** [comment]
My apologies for the delay, finally getting around to updating.  Can you provide your use case?
