### ISSUE TITLE
TVP issues

### ISSUE THREAD

**Issue by Jetski5822** [dallasbeek/Dapper.Database#20]
Hey - Having a problem with using a TVP;

Using a profiler, whats produced looks like this;

declare @p3 dbo.IdTVP
insert into @p3 values(5)
insert into @p3 values(8)
insert into @p3 values(13)
insert into @p3 values(27)
insert into @p3 values(29)
insert into @p3 values(37)
insert into @p3 values(39)
insert into @p3 values(40)
insert into @p3 values(41)
insert into @p3 values(43)
insert into @p3 values(44)
insert into @p3 values(45)
insert into @p3 values(46)
insert into @p3 values(47)
insert into @p3 values(48)
insert into @p3 values(52)

exec sp_executesql N'SELECT e.* FROM [txhr0emp] e INNER JOIN @personIdsTVP ptvp ON e.pers_no = ptvp.Id',N'@personIdsTVP [dbo].[IdTVP] READONLY',@personIdsTVP=@p3

but in code, the values returned are not mapped...

            return _dbConnection.GetList<Employee>(sql: @"
                SELECT e.* FROM [txhr0emp] e
                INNER JOIN @personIdsTVP ptvp ON e.pers_no = ptvp.Id",
                parameters: new { personIdsTVP = itemDataTable.AsTableValuedParameter("[dbo].[IdTVP]") });

**Comment by dallasbeek** [comment]
I'm assuming this is MS SQL Server.  I whipped up a test and I don't think it's an issue with the code as I was able to retrieve data using a TVP.  I'm leaning toward you having an issue with the type definition. 

You should have a User type defined similar to this.
`CREATE TYPE dbo.IdTVP AS TABLE 
(
	Id int
    PRIMARY KEY (Id)
)
GO`

Here is what I used to test
Database
`CREATE TYPE dbo.ProductIdTable AS TABLE 
(
	ProductId int
    PRIMARY KEY (ProductId)
)
GO`

See Checkin above.
