### ISSUE TITLE
Examples for generated SQL in docs

### ISSUE THREAD

**Issue by Gameghostify** [dallasbeek/Dapper.Database#22]
It might be worth adding some examples for generated SQL queries in the docs.

For example, before digging through some code, it wasn't clear whether or not the actual list of columns was `SELECT`ed, or a `SELECT *` query would be generated (like [Dapper.Contrib currently does](https://github.com/StackExchange/Dapper/issues/482)).

What do you think?

**Comment by dallasbeek** [comment]
Good idea, It's probably not clear what the attributes do in terms of IgnoreUpdate/IgnoreInsert/IgnoreSelect and DatabaseGenerated do.
