### ISSUE TITLE
Nested Select Statements dont play well

### ISSUE THREAD

**Issue by Jetski5822** [dallasbeek/Dapper.Database#24]
```sql
            return await DbConnection
                .GetAsync<EmployeeWeek>(@"WHERE emp_wk_no = (
                        SELECT max(emp_wk_no) from txhr0emw
                         WHERE is_temporary = 0
                           AND emp_no = @employeeId)", new { employeeId }, transaction)
                .ConfigureAwait(false);
```

Produces this;

exec sp_executesql N'WHERE emp_wk_no = ( SELECT max(emp_wk_no) from txhr0emw WHERE is_temporary = 0 AND emp_no = @employeeId)',N'@employeeId int',@employeeId=10001

**Comment by dallasbeek** [comment]
The SQL parser isn't overly advanced.  The presence of the SELECT in the subquery makes the logic think you have supplied a full query.  The easy correction to the above is to supply the outer select
"; SELECT * FROM EmployeeWeek WHERE emp_wk_no = (........"  
* note the first character semicolon will short circuit the parser completely

It's my opinion that a fully advanced SQL parser, especially one that can parse all database nuances, would probably not perform well.

**Comment by Jetski5822** [comment]
Ah - interesting, thanks
