### ISSUE TITLE
Return Identity from Insert

### ISSUE THREAD

**Issue by aldrin-ronco** [dallasbeek/Dapper.Database#25]
Hello,

First of all thank you and congratulations on maintaining this package, it really helps a lot.

Please excuse me if this is not the appropriate channel to ask questions, but I can't find any link to answer questions.

I have done Google searches related to this package but I have not been able to obtain information.

My question is the following: How can I use the Insert method but instead of returning a bool, return the Id of the created record?

Thank you so much

**Comment by dallasbeek** [comment]
I assume you are talking about an Identity Column. Decorate your class with a [DatabaseGenerated(DatabaseGeneratedOption.Identity)] attribute and the property will be set for you. In MS SQL the query produced includes an output clause. See the first test case in this file https://github.com/dallasbeek/Dapper.Database/blob/master/Dapper.Database.Tests/Tests/TestSuiteInsert.cs.


```
    [Table("Person")]
    public class PersonIdentity
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdentityId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }

```

**Comment by aldrin-ronco** [comment]
Nice, thanks for your help, great package.

**Comment by Anda001** [comment]
but if the table use some triggers when insert, it turns out to some error.
I debug into the code which use output from inserted to get id.
``` 
protected override string BuildInsertQuery(TableInfo tableInfo)
            => tableInfo.GeneratedColumns.Any()
                ? $"insert into {EscapeTableName(tableInfo)} ({EscapeColumnList(tableInfo.InsertColumns)}) output {EscapeColumnListWithAliases(tableInfo.GeneratedColumns, "inserted")} values ({EscapeParameters(tableInfo.InsertColumns)}) "
                : base.BuildInsertQuery(tableInfo); 
```

the error shows
`
If a DML statement contains an output clause without an into clause, the target table of the statement cannot have any enabled triggers
`

**Comment by Anda001** [comment]
``` 
protected override string BuildInsertQuery(TableInfo tableInfo)
            => tableInfo.GeneratedColumns.Any()
                ? $"insert into {EscapeTableName(tableInfo)} ({EscapeColumnList(tableInfo.InsertColumns)}) values ({EscapeParameters(tableInfo.InsertColumns)});select SCOPE_IDENTITY() as Id "
                : base.BuildInsertQuery(tableInfo); 
```

for sql server I use "select SCOPE_IDENTITY() as Id" seems more reasonable.

**Comment by dallasbeek** [comment]
I'm able to reproduce this.  I like the output because it also returns other generated columns and I feel it probably performs better. Since this is likely an exception than a rule I'm thinking about addressing this with a custom Entity Attribute.
Let's say something like

[SelectGeneratedColumnsAttribute] 
class Foo {

}

which instead of doing "output inserted.Id" does something like the SqlCEServerAdapter does.  Any thoughts?

       ```
     var command = new StringBuilder(InsertQuery(tableInfo));

            if (tableInfo.GeneratedColumns.Any())
            {
                var selectCommand =
                    new StringBuilder(
                        $"select {EscapeColumnListWithAliases(tableInfo.GeneratedColumns, tableInfo.TableName)} from {EscapeTableName(tableInfo)} ");

                selectCommand.Append(tableInfo.KeyColumns.Any(k => k.IsIdentity)
                    ? $"where {EscapeColumn(tableInfo.KeyColumns.First(k => k.IsIdentity).ColumnName)} = @@IDENTITY;"
                    : $"where {EscapeWhereList(tableInfo.KeyColumns)};");

                var wasClosed = connection.State == ConnectionState.Closed;
                if (wasClosed) connection.Open();

                connection.Execute(command.ToString(), entityToInsert, transaction, commandTimeout);
                var r = connection.Query(selectCommand.ToString(), entityToInsert, transaction,
                    commandTimeout: commandTimeout);

```

**Comment by dallasbeek** [comment]
Published a new package, there are two ways you can avoid the DML output issue. 

Globally
`SqlDatabase.SqlServerSelectComputed = true;`

Or on an individual table
```
[Table("Account")]
[SqlServerSelectComputed]
public class AccountModel
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int AccountId { get; set; }

    public string FirstName { get; set; }
    public string LastName { get; set; }
}

```
