### ISSUE TITLE
Can the Apache 2.0 license be replaced by the MIT license?

### ISSUE THREAD

**Issue by TripleView** [dallasbeek/Dapper.Database#27]
I like this project very much, and at the same time I hope to change it more arbitrarily, and add it to my own project (MIT agreement), so, can I change the license to MIT?

**Comment by dallasbeek** [comment]
I'm not opposed to MIT license but the license for this was chosen to match Dapper so as to not create added confusion. I thought Dapper allowed for MIT (which I see mentioned on [Wikipedia](https://en.wikipedia.org/wiki/Dapper_ORM)) but I can't find anything on the github repository.
