### ISSUE TITLE
GetListAsync StoreProcs

### ISSUE THREAD

**Issue by Jetski5822** [dallasbeek/Dapper.Database#28]
Hey just went to use GetListAsync  with a stored proc, but for some reason you arent exposing the command type? Is there a way to pass it in?

**Comment by dallasbeek** [comment]
Dapper handles this and I've never encountered an issue calling a stored procedure.  I think it uses Text as the command type but the way I call a stored procedure using Dapper.Database is with Exec

`  var settingsList = await database.GetListAsync<Setting>("; EXEC [App].[GetSettings] @param", new {param = 1});`

_the semicolon as the first character in the SQL query will short circuit logic that tries to build the select clause.  It should still work if you don't set the first character as a semicolon but less performant._

most of time I don't need a stored procedure and will supply a WHERE AND ORDER BY like this

`  var settingsList = await database.GetListAsync<Setting>("WHERE [Param] = @param ORDER BY [Name], new {param = 1});`

**Comment by Jetski5822** [comment]
Ah- so use Text, not as nice as Query<> where you can just pass params, but it works. Thanks :)
