### ISSUE TITLE
Setting a datetime to null, makes the type passed in as nvarchar(4000)

### ISSUE THREAD

**Issue by Jetski5822** [dallasbeek/Dapper.Database#30]
We have a scenario where we set the datetime to null, using the UpdateAsync method on SQLServer; and this is what we see.

Setting the EndDateTimeUtc to not null:

exec sp_executesql N'update [dbo].[Assignments] set [BadgeVersionNumber] = @BadgeVersionNumber, [StartDateTimeUtc] = @StartDateTimeUtc, [EndDateTimeUtc] = @EndDateTimeUtc, [TeamName] = @TeamName, [JobCode] = @JobCode, [JobName] = @JobName where [AssignmentId] = @AssignmentId',N'@AssignmentId nvarchar(4000),@BadgeVersionNumber int,@EndDateTimeUtc datetime2(7),@JobCode nvarchar(4000),@JobName nvarchar(4000),@StartDateTimeUtc datetime2(7),@TeamName nvarchar(4000)',@AssignmentId=N'4vhb5ywt2p1r8zrg31naer7jny',@BadgeVersionNumber=90,@EndDateTimeUtc='2020-09-06 00:00:00',@JobCode=N'ABC',@JobName=N'Some jobby',@StartDateTimeUtc='2020-02-10 00:00:00',@TeamName=N'Some updated team'

Setting the EndDateTimeUtc to null (heres the issue):

exec sp_executesql N'update [dbo].[Assignments] set [BadgeVersionNumber] = @BadgeVersionNumber, [StartDateTimeUtc] = @StartDateTimeUtc, [EndDateTimeUtc] = @EndDateTimeUtc, [TeamName] = @TeamName, [JobCode] = @JobCode, [JobName] = @JobName where [AssignmentId] = @AssignmentId',N'@AssignmentId nvarchar(4000),@BadgeVersionNumber int,@EndDateTimeUtc nvarchar(4000),@JobCode nvarchar(4000),@JobName nvarchar(4000),@StartDateTimeUtc datetime2(7),@TeamName nvarchar(4000)',@AssignmentId=N'4f13hn9xk9cw6yvj0yfgwxm4wy',@BadgeVersionNumber=90,@EndDateTimeUtc=NULL,@JobCode=N'ABC',@JobName=N'Some jobby',@StartDateTimeUtc='2020-02-10 00:00:00',@TeamName=N'Some updated team'

Note here: @EndDateTimeUtc nvarchar(4000)

**Comment by dallasbeek** [comment]
I don't think the nvarchar(4000) would be something my library would be doing. This seems like it would be done further down the chain and possibly by a microsoft library.

Are you using a SqlMapper?
            SqlMapper.AddTypeMap(typeof(DateTime), DbType.DateTime2);

**Comment by Jetski5822** [comment]
Ah - its because Dapper doesnt know what type "Null" is... so wont call the type handler; bit stupid.
