### ISSUE TITLE
One-to-Many GetList

### ISSUE THREAD

**Issue by aboah** [dallasbeek/Dapper.Database#31]
Please how can we use your library as GetList<T,T,Tresult>(where clause) for one-to-many mapping.
Your documentation provides example for one-to-one mapping.

 var lst = db.GetList<Product, ProductCategory, ProductModel, Product>(
                    (pr, pc, pm) =>
                    {
                        pr.ProductCategory = pc;
                        pr.ProductModel = pm;
                        return pr;
                    },
                    GetListMultiThreeParamQuery, new { Color = "Black" }, "ProductCategoryId,ProductModelId");

**Comment by dallasbeek** [comment]
Many ways of accomplishing that but probably most efficient is using GetFirst.  See GetFirstTwoJoinsMapped
https://github.com/dallasbeek/Dapper.Database/blob/master/Dapper.Database.Tests/Tests/TestSuiteGetFirst.cs

**Comment by dallasbeek** [comment]
See Multiple Relationships here https://www.learndapper.com/relationships  I think that will help you understand how to use GetList to accomplish what you want.  Alternatively I would use GetMultiple
something like this.

```
            var multiData = await _flexRepository.GetMultipleAsync(
                @"SELECT * from A WHERE [Id] = @id;
                SELECT * FROM B WHERE [IncidentId] = @id;", new { id });

            var incident = (await multiData.ReadAsync<Incident>()).SingleOrDefault();
            if (incident != null)
            {
                incident.Tags = (await multiData.ReadAsync<Taxonomy>()).ToList();
            }

            return incident;

```
