### ISSUE TITLE
Guid PK support?

### ISSUE THREAD

**Issue by GusBeare** [dallasbeek/Dapper.Database#32]
Hi
Before I have a go can you tell me if this libary works with Guid PK's?
I am not using integers.

thanks
Gus

**Comment by dallasbeek** [comment]
Yes, it's one of the primary reasons I created it instead of using Dapper Contrib.

**Comment by dallasbeek** [comment]
I also primarily use Guid PK's in my projects.

**Comment by GusBeare** [comment]
Many thanks. I'll check it out.  I am wanting to use Guids for the pros but am wary of the potential problems.  Do you use PK's like this?

    alter table add guid uniqueidentifier default newsequentialid() primary key clustered

**Comment by dallasbeek** [comment]
I don't use a default, I always initialize it in code.
Id = Guid.NewGuid()

By setting it in code I can then use the Upsert Methods and have a common save method.
```
     await _repo.UpsertAsync(incident,
                create => create.CreatedOn = DateTime.Now,
                update => update.UpdatedOn = DateTime.Now);
```

However, I don't think it would matter to have a default, would prevent you from accidentally inserting 000-0000

**Comment by dallasbeek** [comment]
Check out the ContactApp in this repository, it's a pretty fair example of how I use uniqueidentifier columns.

**Comment by GusBeare** [comment]
Very cool and well helpful thanks!

**Comment by GusBeare** [comment]
It works well thank you.  I noticed that by default is uses the pluralised name of the db table. So if I have a model and a table called Franchise. The sql generated looks for a table called "Franchises".  Unless I do this:

     [Table("Franchise", Schema = "dbo")]
    public class Franchise
    {
        [Key]
        public Guid Guid { get; set; }
       ...

Is there a way I can set it to not use the plural name by default to avoid these annotations?

**Comment by dallasbeek** [comment]
This was intentionally done to backward support those that might be coming over from Dapper.Contrib.  I checked Dapper.Contrib and they still are doing this even though I completely disagree.  See function GetTableName
https://github.com/DapperLib/Dapper.Contrib/blob/main/src/Dapper.Contrib/SqlMapperExtensions.cs  

Not sure if you have seen the code generator (tt template) but it takes a lot of pain out of coding your POCO classes if you have an established database.

**Comment by GusBeare** [comment]
Shame. I agree with you on that one.   Yes I have seen the tt. Very powerful. I am new to t4 but have been working through some examples and building my own. cheers for the great tool.
