### ISSUE TITLE
can we set IgnoreUpdate in code 

### ISSUE THREAD

**Issue by Anda001** [dallasbeek/Dapper.Database#38]
when I update the entity,it tells id can't be updated.
I didnot set  "columnsToUpdate",but we always not to update the id KEY,don't we?
so if we can add  columnsToUpdate why there are not columntsNotToUpdate?

**Comment by Anda001** [comment]
or we  set IgnoreUpdate to the KEY id column as default action when do update.

**Comment by dallasbeek** [comment]
The key column should be ignored on update if it is attributed correctly

        [Column] [Key] public Guid Id { get; set; }

or for identity column

        [Column, Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

**Comment by Anda001** [comment]
yes.the second  solution works well by add "DatabaseGenerated(DatabaseGeneratedOption.Identity".
but sometimes we don't want to change the models,especially the models are auto-generated.

and have you read this  [issue.](https://github.com/dallasbeek/Dapper.Database/issues/25#issuecomment-1178454160)
insert or update with triggers.

**Comment by dallasbeek** [comment]
Reopened other issue for investigation, closing this one
