### ISSUE TITLE
how to use select from other sql result

### ISSUE THREAD

**Issue by Anda001** [dallasbeek/Dapper.Database#39]
sth like this:

```   
 var bianhao = "1602190120211908";
 var sq=$@"select by_etor.* from by_etor  where dtu_id in (select id from by_dtu where bianhao= '{dtu_bianhao}'";   
```

this can be exceuted in dapper ,but as there no property-column mapper,so I can't get the right object.  don't know how to implement in Dapper.Database,like 
``` 
var eModel = dbCon.GetFirst<ByEtor>(sq); 
``` 
this will throw exception in "where " .

**Comment by dallasbeek** [comment]
Don't do this, this is open to sql injection
`var sq=$@"select by_etor.* from by_etor  where dtu_id in (select id from by_dtu where bianhao= '{dtu_bianhao}'";
`

given a class Bianhao with attribute mappings

```

[Table("somedbtable"]
class Bianhao { ** properties ** }

var bianhao = "1602190120211908";

var entity = dbCon.Get<Bianhao>(banhao)
or
var entity = dbCon.Get<Bianhao>("where id = @id", new {id=bianhyao});
or
var entity = dbCon.GetFirst<Bianhao>("where id = @id", new {id=bianhyao});
or
var entity = dbCon.GetFirst<Bianhao>("where id = @id", new {id=bianhyao});
```

What database are you targeting?

**Comment by dallasbeek** [comment]
Adding a semicolon at the beginning of the query "; select" will short circuit the logic that attempts to substitute variables and where clause.

**Comment by Anda001** [comment]
I use sqlserver.

there two tables. One is 'by_dtu',another is 'by_etor'.
the sql string I used above is to to get a by_dtu object throught dtu_bianhao.
then get by_etor through by_dtu object 's Id.
``` 

 var bianhaoStr = "1602190120211908";
var by_dtu=dbCon.GetFirst<by_dtu>("where bianhao = @bianhao", new {bianhao=bianhaoStr});
var by_etor=dbCon.GetFirst<by_etor>("where dtu_id = @dtu_id", new {dtu_id=by_dtu.id});
 ```

but I hope we can combine the two steps to one.

**Comment by dallasbeek** [comment]
not sure if you need both objects back.  if you only need by_etor then
```

dbCon.GetFirst<by_etor>(@"; select etor.* 
from by_dtu dtu
join by_etor etor on etor.dtu_id = dtu.id
where dtu.bianhao= @bianhao", new{bianhao=bianhaoStr});
```
