### ISSUE TITLE
Missing adapters

### ISSUE THREAD

**Issue by denis-taran** [dallasbeek/Dapper.Database#4]
The NuGet package is outdated and doesn't include certain adapters like PostgreSQL. Could you please republish it with new adapters? The new version has also added an additional dependency - `FirebirdSql.Data.FirebirdClient`. Usually, micro-orms doesn't include such dependencies and do all the work via `IDbConnection`, otherwise all those dependencies must be copied during deployment, even if you don't use any of them. It would be nice if this dependency could be removed.

**Comment by dallasbeek** [comment]
Published nuget package Install-Package Dapper.Database -Version 0.10.0-alpha-00073.  I think you are right about the Firebird dependency, don't think it should be there.  I need to test that on a different machine so will look into it over the weekend.  I've started some work on an Oracle adapter.  Would you like to share yours?  I'm not too experienced in Oracle but the main things I see is changing @Parameter to :Parameter and on insert doing something similar to PetaPoco using a Sequence Attribute to get identity value.  That code is here https://github.com/CollaboratingPlatypus/PetaPoco/blob/development/PetaPoco/Providers/OracleDatabaseProvider.cs (GetAutoIncrementExpression)

**Comment by dallasbeek** [comment]
Latest nuget package fixes alias column issues as well as removed the Firebird package.
Install-Package Dapper.Database -Version 0.10.0-alpha-00079
