### ISSUE TITLE
is this a problem ?

### ISSUE THREAD

**Issue by Anda001** [dallasbeek/Dapper.Database#40]
seems not grace release the connection?

![image](https://user-images.githubusercontent.com/1329895/180726119-95e41cfe-4b51-460e-b503-7b0ae34e0eda.png)

**Comment by dallasbeek** [comment]
I see MassTransit involved so things can be complicated here. If this is a Consumer are you sure you have all the dependency injection wired up? If you are executing a series of Async methods try wrapping them with a transaction, that should hold the connection open.

    ```
    using var trans = _repo.GetTransaction();
        var multiData = await _repo.GetMultipleAsync(
            sqlQuery, new { id });

        var activity = (await multiData.ReadAsync<Activity>()).SingleOrDefault();
        if (activity != null) activity.Tags = (await multiData.ReadAsync<Tag>()).ToList();

        trans.Complete();
```

**Comment by Anda001** [comment]
first time I met the problem I thaught I release the connection more than once,but I don't know Where the problem lies.
 
1) yes,MassTransit  involved,but none of my code showed in the picture,and I think we can trust the libs.
2) as a message consumer,most of the time they run OK,so dependency injection wired up without questions.
3) that's maybe the point,we use async method,some of the message handle  takes a long time.but use transaction maybe not a good idea.  
or should we new a connection each time?

**Comment by dallasbeek** [comment]
I'd wrap with a transaction but if you are concerned about transactions causing locks then I'd open a new connection. Also check the registration of your IConnectionService, I suggest SingleInstace (i.e. Singleton).

**Comment by Anda001** [comment]
OK.tks,I will try.

**Comment by wuzhenda** [comment]
OK.I will try.

**Comment by Anda001** [comment]
as the first picture  show the line 113  has problem. so I add try-catch  solution, and the log shows the exception line at 113.

![image](https://user-images.githubusercontent.com/1329895/181458956-a4bd2533-0079-4bea-a10a-9e1ab75ea9be.png)

but the line 113  is connection-dispose, and the line 112 is  connection-close.

so I comment the line 112.  things go OK.


refs:
[https://social.msdn.microsoft.com/Forums/en-US/0ac356d2-6054-4f98-939b-120c1a87a3a3/do-i-need-to-dispose-sqlconnection?forum=aspgettingstarted#:~:text=In%20case%20of%20SQLConnection%20object%20both%20close%20and,don%27t%20really%20need%20to%20call%20the%20dispose%20method.](https://social.msdn.microsoft.com/Forums/en-US/0ac356d2-6054-4f98-939b-120c1a87a3a3/do-i-need-to-dispose-sqlconnection?forum=aspgettingstarted#:~:text=In%20case%20of%20SQLConnection%20object%20both%20close%20and,don%27t%20really%20need%20to%20call%20the%20dispose%20method.)

**Comment by dallasbeek** [comment]
Thanks for this, I'll run some tests across other databases and make sure we don't introduce side effects. I'm pushing to get an update next week.
