### ISSUE TITLE
SQL column aliasing dependency?

### ISSUE THREAD

**Issue by jvukovich** [dallasbeek/Dapper.Database#42]
Hello, I am new to Dapper. My team and I are looking at replacing our existing ORM (PetaPoco) with it.

While researching, I came across this project and liked what I saw regarding table and column aliasing, as well as all the handy extension methods. Very nice, thanks!

We hit a snag, though. Let's say I have an object with a column alias like so:
```
public class Actor
{
  public int Id { get; set; }

  [Column("Nickname")]
  public string Name { get; set; }
}
```

In C#, we query like this:
`db.GetList("select * from Actor");`

However, on execution, the property Name returns null.

If we do it like, this, though, it works (returns values):
`db.GetList("select [Name] as [Nickname], * from Actor");`

Is there a way in Dapper itself, or in Dapper.Database, to have it resolve the mapping(s) without depending on SQL column aliasing?

Thank you!

**Comment by dallasbeek** [comment]
For simple selects you do not have to provide a select clause.  Try this
` db.GetList<Actor>("ORDER BY [Id]"); `

or with where
` db.GetList<Actor>("WHERE [Id] > @id ORDER BY [Id]", new{id=33}); `


If you do supply a select clause you will need to provide alias for the mapping to work.

**Comment by jvukovich** [comment]
Okay, thank you!

I did manage to get it to work following this:
https://gist.github.com/kalebpederson/5460509

I'll send your info to the team and see if they're up for a refactor. Thanks again! I appreciate the help, and the great work on this extension project! <3
