### ISSUE TITLE
Bulk Insert Feature

### ISSUE THREAD

**Issue by denis-taran** [dallasbeek/Dapper.Database#7]
It would be nice if the library could insert multiple entities at once, for example:

    var items = (IEnumerable<MyEntity>) result;
    await connection.BulkInsertAsync(items);

and then it would generate the following SQL code:

    INSERT INTO ... (...) VALUES (...);
    INSERT INTO ... (...) VALUES (...);
    ...

It can also be made with transactions like this:

    BEGIN;
        INSERT INTO ... (...) VALUES (...);
        INSERT INTO ... (...) VALUES (...);
        ...
    COMMIT;

**Comment by dallasbeek** [comment]
I made an initial attempt at this and my findings were that I wouldn't be able to bring back calculated columns (i.e. first name) without opening a transaction (for purposes of rollback on error) and looping against against my insert query.  Let me do some more research but bulk insert is a tricky thing and in reality there are much more efficient ways to do bulk insert.  Let me give it some more thought though.

**Comment by dallasbeek** [comment]
InsertList, InsertListAsync, UpdateList, UpdateListAsync, UpsertList and UpsertListAsync are available in my development branch.  Still have some tests to fix.

**Comment by dallasbeek** [comment]
merged and updated on nuget
