### ISSUE TITLE
Deletes are deleting all rows/data in a table

### ISSUE THREAD

**Issue by HudsonAkridge** [dallasbeek/Dapper.Database#8]
Specifically this is with either the Primary Key, or Composite Key, or By Entity deletes. Library isn't respecting the keys, and so performs an unbounded `DELETE FROM <tablename>` with no WHERE query.

Additionally, there's no obvious/clean way to do a delete all with the given interface. Having an explicit DeleteAll() would go a long way towards making sure someone didn't accidentally delete everything :)

Looking at the Delete Tests, it appears that those tests currently pass because it's not checking that there is still other remaining data in the table after a bounded delete was issued. By adding some additional data inserted in the tests, we can quickly see that the DeleteByUniqueKey, PrimaryKey, CompositeKey, etc. are actually removing all rows in the table, not just the one you've asked it to.

**Comment by gt6796c** [comment]
@dallasbeek  I just ran into this on mainline. I see that development might have a different PR applied that addresses this. Any timeline for releasing that through nuget?

**Comment by HudsonAkridge** [comment]
Correct. This is only happening on master. There's a version of this PR on the `development` branch that pulls in all of the changes on this PR, with some additional feedback of naming/overload tweaks that were requested and discussed with @dallasbeek . There's also one or two small bug fixes contained on the `development` branch for deletes that aren't included here.

Not sure about the nuget timeline on merging development down into master and getting a release though. I believe there was an issue with one of the changes made to the `SqlAdapter`s that @cdonnellytx had to get in all of the new Oracle Support which broke versions of MsSql earlier than 2008 that @dallasbeek was looking to fix before merging.

If you needed, you could grab the `development` branch as is and you'd get all of the DeleteFixes contained here (as long as you're not using MsSql2005 I suppose).

**Comment by cdonnellytx** [comment]
@HudsonAkridge `development` supports SQL Server than 2012, just add this line to the startup phase of your code:

```csharp
SqlMapperExtensions.AddSqlAdapter<SqlConnection>(new SqlServerPre2012Adapter());
```

It should work with 2005 and later.

**Comment by HudsonAkridge** [comment]
Ah, perfect! Thanks @cdonnellytx .

**Comment by dallasbeek** [comment]
I was going to get Insert/Update/Upsert List before merging to master but I don't want to be rushed on it so I will go ahead and do the update now.

**Comment by dallasbeek** [comment]
Install-Package Dapper.Database -Version 0.10.0-alpha-00117
